### ISSUE TITLE
The documentation can be improved.

### ISSUE THREAD

**Issue by busi-reddy-karnati** [SafeExamBrowser/Chrominimum#11]
I think the documentation can be improved. It doesn't say how to use SEB and chrominimum, although an issuse addresses it. But I think it will be better to improve the README. 
Let me know if I can contribute to that.

**Comment by dbuechel** [comment]
I'll see whether I can add some info to the readme. Though that part imho belongs to the configuration of SEB which is explained exhaustively in the user manual.

**Comment by busi-reddy-karnati** [comment]
Thanks for considering.
