### ISSUE TITLE
Mac OS X Version

### ISSUE THREAD

**Issue by senapetschnig** [SafeExamBrowser/Chrominimum#14]
We are already succesfully using the chrominimum for webrtc in seb on windows.
But i don't see a chance for webrtc on mac os x, am i'm missing/misconfiguring something or is webrtc not working on mac os x seb?
If not, is there a chance to build chrominimum also for mac os x?
Best regards and thanks a lot for SEB and Chrominimum!!!

**Comment by dbuechel** [comment]
Unfortunately, there isn't a build for macOS as there currently also isn't an option to use third-party applications with SEB for macOS.
