### ISSUE TITLE
IndexedDB quota reporting a tiny amount of space.

### ISSUE THREAD

**Issue by keean** [SafeExamBrowser/Chrominimum#15]
When I start my application in Chrominimum, IndexedDB is allowed only a tiny quota (50MB?). Safe Exam Browser 3 reports a quota of 25GB on the same platform.

At the moment this gives us no way to run exams using SEB, as WebRTC is not supported by SEB, and IndexedDB is quota-limited to an unusably small size by Chrominimum.

We have discussed elsewhere the difficulties of supporting WebRTC in SEB, so is it possible to fix the storage quota in Chrominimum to return the same as SEB, so that we have some way of running these exams?

**Comment by dbuechel** [comment]
This might have to do with the fact that Chrominimum is currently only using an in-memory cache. I'll see whether I can improve this for the next release.

**Comment by dbuechel** [comment]
I implemented a new parameter (`--store-cache`) in version 1.1.1 with which you can force the browser cache to be saved on disk. I reckon this should fix the issue with the quota. If not, feel free to reopen the issue and we'll look further into the matter.
