### ISSUE TITLE
Downloads not available in chrominimum

### ISSUE THREAD

**Issue by mukeshkannan-web** [SafeExamBrowser/Chrominimum#18]
Hi 
We facing an issue using chromonimum browser for downloading the files. Download feature is  not available. If it is available its better for our use cases

Device: Desktop - pc
OS Version: Windows 10 
Chrominimum Version: 1.1.1.30
SEB Version:3.xx

**Comment by dbuechel** [comment]
As we will be able to enable WebRTC for the upcoming SEB version 3.2 we'll most likely stop development of Chrominimum and this issue should thus become obsolete.

**Comment by dbuechel** [comment]
The latest SEB version 3.2.0 now provides WebRTC functionality, Chrominimum has thus become obsolete.
