### ISSUE TITLE
WebRTC BBB not prompting user to share microphone/webcam.

### ISSUE THREAD

**Issue by andrewmadden** [SafeExamBrowser/Chrominimum#3]
We successfully had chrominimum launch inside SEB Windows 3.0.1 to a valid BBB session. However when prompted to select the microphone, the user was not presented with a pop up asking them to allow the site to access their hardware. 

Is there anything we can do to troubleshoot why the browser isn't prompting the user to provide access?

Do you have an example of this application working as expected?

**Comment by dbuechel** [comment]
I think all popups are blocked in the current implementation. Can you provide a step-by-step instruction on how it is supposed to work and what exactly isn't working?

**Comment by andrewmadden** [comment]
I am unable to show screenshots of the WebRTC application at this stage for privacy reasons.

Expected:
1. Browser joins WebRTC session. 
2. Browser has pop up prompting user to  allow access to microphone (This is required by all WebRTC applications)
3. User  is  able to choose their microphone in a UI
4. Browser has pop up prompting user to  allow access to cam (This is required by all WebRTC applications)
5. User  is  able to choose their cam in a UI
6. User is able to see/hear others in session

Actual:
1. Browser joins WebRTC session.
2. Error is shown to  user  saying they are unable to connect to a microphone.

Setup:
In SEB, added an allowed process for chrominimum including a parameter  of the WebRTC session  join link.

EDIT:
May be issues with BBB configuration. I'll get back to you, and close this if we find a fix. Thanks.

**Comment by andrewmadden** [comment]
With some configuration changes, we were able to share audio and video with a basic Big Blue Button session. However we still had an issue with sharing a screen. Is it assumed that Chrominimum will be able to share screens via WebRTC?

**Comment by akashif** [comment]
I am also stuck with sharing a screen, "Allow screen Sharing" popup never appears, As all type of popups are disabled, any workaround for sharing a screen?

**Comment by dbuechel** [comment]
I don't think screen sharing is supported by the implementation in CEF (the parameter for the engine is also called "enable-media-stream").

**Comment by dbuechel** [comment]
Any further questions here, or can we close the issue?

**Comment by dbuechel** [comment]
Closed due to lack of feedback.

**Comment by Tod8Cruz** [comment]
@andrewmadden How did you change configuration to be able to share audio and video?
