### ISSUE TITLE
Screen Sharing option not supported

### ISSUE THREAD

**Issue by salluashik** [SafeExamBrowser/Chrominimum#4]
Screen Sharing Option not supported. When using Exam URL in chrome , Normally a prompt comes asking permission to share screen. But in Chrominimum this feature not enabled or not allowed. please help.

**Comment by dbuechel** [comment]
I don't think screen sharing is supported by CEF, but you'd need to check there. If it's just another command-line parameter to enable, we can certainly add it to Chrominimum.

**Comment by dbuechel** [comment]
I closed this issue since it is a duplicate of #3
