### ISSUE TITLE
Google meet issue

### ISSUE THREAD

**Issue by intarian** [SafeExamBrowser/Chrominimum#6]
Hi! I am trying to run Google meet on this for proctoring purpose and it says browser is not supported. I think the version is outdated, can you push the updated binaries?

**Comment by dbuechel** [comment]
I updated the browser engine to the latest version, see https://github.com/SafeExamBrowser/Chrominimum/releases/tag/1.0.1

**Comment by intarian** [comment]
Thank you so much for the quick response. Unfortunately, I am still unable to start the video call on Google meet. Even on Google sign-in page says: This browser or app may not be secure. I am a noob here, so not sure what could be the problem here. Do you have any hints?

**Comment by dbuechel** [comment]
Unfortunately not, I have no experience with Google Meet. You could try their official support, if they have one.

**Comment by intarian** [comment]
Did you test any proctor tools with this chromium-browser beside google meet?

**Comment by dbuechel** [comment]
I personally only verified that WebRTC is working.

**Comment by intarian** [comment]
I have also checked with native support of webcam and everything works. The problem is coming from Google side. I googled the issue and found this solution: https://stackoverflow.com/questions/59480956/browser-or-app-may-not-be-secure-try-using-a-different-browser-error-with-fl

I would have looked into this myself but I don't have the build ready, can you check that is there any **remote-debugging** parameter turned on?

**Comment by dbuechel** [comment]
No, we don't use remote debugging.

**Comment by intarian** [comment]
Yes you are right. I just checked with cef_binaries; and google meet doesn't work there. It looks like the fault is at cef end. Thanks for the help.
